sudo: required
cache:
  - bundler

language: ruby
bundler_args: --without development

before_install:
  - gem install bundler

before_script:
  - psql -c 'create database vampart_test;' -U postgres
  - bundle exec rake db:test:load_schema
  - bundle exec rake db:seed
  - mkdir -p public/uploads/images
  - docker network create vampart_openface_api
  - docker-compose up -d
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - bundle exec rspec spec

addons:
  postgresql: '9.4'

services:
  - docker
